"""added join table

Revision ID: 23a86de44e4c
Revises: 0a3174a8960f
Create Date: 2024-03-21 15:20:34.555924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a86de44e4c'
down_revision = '0a3174a8960f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys_age_ranges',
    sa.Column('toy_id', sa.Integer(), nullable=False),
    sa.Column('age_range_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_range_id'], ['age_ranges.id'], name=op.f('fk_toys_age_ranges_age_range_id_age_ranges')),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], name=op.f('fk_toys_age_ranges_toy_id_toys')),
    sa.PrimaryKeyConstraint('toy_id', 'age_range_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys_age_ranges')
    # ### end Alembic commands ###
