"""all the columns at once

Revision ID: 7b424921b5fb
Revises: 86a5a70416ae
Create Date: 2024-04-01 11:42:40.207635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b424921b5fb'
down_revision = '86a5a70416ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.primaryKeyConstraint('id', name=op.f('pk_age_ranges'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.primaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_toys_user_id_users')),
    sa.primaryKeyConstraint('id', name=op.f('pk_toys'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('toy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], name=op.f('fk_reviews_toy_id_toys')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.primaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('toys_age_ranges',
    sa.Column('toy_id', sa.Integer(), nullable=False),
    sa.Column('age_range_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_range_id'], ['age_ranges.id'], name=op.f('fk_toys_age_ranges_age_range_id_age_ranges')),
    sa.ForeignKeyConstraint(['toy_id'], ['toys.id'], name=op.f('fk_toys_age_ranges_toy_id_toys')),
    sa.primaryKeyConstraint('toy_id', 'age_range_id', name=op.f('pk_toys_age_ranges'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys_age_ranges')
    op.drop_table('reviews')
    op.drop_table('toys')
    op.drop_table('users')
    op.drop_table('age_ranges')
    # ### end Alembic commands ###
