"""created user columns

Revision ID: 864bacbc45a5
Revises: 45e5fe41da4d
Create Date: 2024-03-21 06:19:00.305790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864bacbc45a5'
down_revision = '45e5fe41da4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
