"""renamed toy column image as image_url

Revision ID: 929be9e8ebe3
Revises: 4d13578d220f
Create Date: 2024-03-21 10:43:32.771912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929be9e8ebe3'
down_revision = '4d13578d220f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
