"""created agerange table

Revision ID: d74c0908d35b
Revises: d35cecdf8ad2
Create Date: 2024-03-21 11:07:12.522361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74c0908d35b'
down_revision = 'd35cecdf8ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('age_groups')
    # ### end Alembic commands ###
