"""renamed agerange table

Revision ID: f4205b4fd26e
Revises: d74c0908d35b
Create Date: 2024-03-21 11:11:49.663353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4205b4fd26e'
down_revision = 'd74c0908d35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('age_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('age_ranges')
    # ### end Alembic commands ###
